{% set python_min = "3.10" %}
{% set name = "satpy" %}
{% set version = "0.54.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: ce0bd652375457550744cb580e7783d7b84ce9dce6f728d58680086285ddd93d

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . --no-deps -vv

requirements:
  host:
    - python {{ python_min }}
    - pip
    - hatchling
    - hatch-vcs
  run:
    - python >={{ python_min }}
    - numpy >=1.21.0
    - pillow
    - pyresample >=1.10.3
    - trollsift
    - trollimage >=1.5.1
    - pyyaml
    - xarray >=0.10.1
    - dask >=0.17.1
    - h5py
    - netcdf4
    - pyspectral
    - pyorbital
    - zarr
    - donfig
    - platformdirs
    - pooch
    - pyproj

test:
  requires:
    - python {{ python_min }}
  imports:
    - satpy
    - satpy.composites
    - satpy.enhancements
    - satpy.readers
    - satpy.writers

about:
  home: https://github.com/pytroll/satpy
  license: GPL-3.0-or-later
  license_family: GPL3
  license_file: LICENSE.txt
  summary: Meteorological processing package
  description: |
    Python package for reading and manipulating meteorological remote
    sensing data and writing it to various image and data file formats.
  doc_url: http://satpy.readthedocs.io/en/latest/
  dev_url: https://github.com/pytroll/satpy

extra:
  recipe-maintainers:
    - djhoese
    - mraspaud
    - adybbroe
    - pnuu
