{% set name = "satpy" %}
{% set version = "0.39.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 8febab8ba166e92a095bc350942c93fc5df9771b62e9746be63a0e7904a438cb

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . --no-deps -vv

requirements:
  host:
    - python >=3.6
    - pip
    - setuptools
    - setuptools_scm
    - setuptools_scm_git_archive
  run:
    - python >=3.8
    - numpy >=1.4.1
    - pillow
    - pyresample >=1.10.3
    - trollsift
    - trollimage >=1.5.1
    - pyyaml
    - xarray >=0.10.1
    - dask >=0.17.1
    - h5py
    - netcdf4
    - pyspectral
    - pyorbital
    - zarr
    - donfig
    - appdirs
    - pooch
    - pyproj

test:
  imports:
    - satpy
    - satpy.composites
    - satpy.enhancements
    - satpy.readers
    - satpy.writers

about:
  home: https://github.com/pytroll/satpy
  license: GPL-3.0-or-later
  license_family: GPL3
  license_file: LICENSE.txt
  summary: Meteorological processing package
  description: |
    Python package for reading and manipulating meteorological remote
    sensing data and writing it to various image and data file formats.
  doc_url: http://satpy.readthedocs.io/en/latest/
  dev_url: https://github.com/pytroll/satpy

extra:
  recipe-maintainers:
    - djhoese
    - mraspaud
    - adybbroe
    - pnuu
