travis:
  secure:
    BINSTAR_TOKEN: pzwlefjuZNdkbOTfgq6Pb1+xwcAPyUZSgZJrXKQHmn98rMctbmW2HvrDJPvG/FglNTH1PKPLk2nShSUj7lzanwEgVYR9jSqvfD1KQQdN3errK4pCXzwo3H7DKqxvlT2SdIUWo5HI6Jf9pAFW7egh3vtYefArA9cRmRjIflR2hiPUbPxFX3R8Xa5lLwJUUPg0FQ3Ef0+xEOEP+oSB9oyRH1B+oYxbBotxfhQJWK0QLMw9eMRLUeC6ObK2/ygRKT23ujvhqnHGDEpu/KP242o2LeBqOiEFn2o/91HqBmjqDmhrqqlssJxHzhHCPmW87yCn2gtYJYJBK0sDhmtLYlTs57e9I3SCwGSEOphHnbq+CRPkV0Rqk5y0+tbp42iCxtl3dUrdlVdiZsu9Ed4G0R5yn5u93kGtfkPOAAq5P6XTdmolhDcoc/LPCF/wxVHJECgEwvNvRELS9pgvJ6Crgxt22TyfzwncEsUYZk2HOrEN6crLBTcoBPUbKJhqtKzKnJU9KwCpQ/ZU8YNRhFmy6QnMPyJ+FRPdauTG/h3iZCkFYNQU06ZZugbqwIyh7cdriTpnecCpjjzw87+VPDXpKK7azbfUIK1yPPWfllcgOnFOG1XcTLT9RyNeVnNi197LSYMh8iNjYmqVgDCQu/qiU+k1c7/yylcWFVSNin2G8oGADOQ=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
conda_forge_output_validation: true
