travis:
  secure:
    BINSTAR_TOKEN: pCUiAg2G3IcgtfGOuclu4XuDKWfGndN/6YOj+/R1TQGwxFe/3dQlHe/0H8DU1OFT+njUwenk1/oxEHtbpg+PUukb86xCSoT99AKtB5OznWbZRSL4bn2+ZxaGQ4CKiRXh1JaHRAW6veSxEp6x/LxCisqTEV6YiY7poMUKWlc6O+McnldRLo1vuJmuPdyt4DnqimK2/rDyKSmjRCsRARhEsrMm2jQ/T2V2K64H6+0myl93+Q1tqHY6AdBr8yZT3993rb+gqnVhGsp56uFrVhM2AFxTk52EmNQI+eJSpVizHbrXr74B1bJdQcHOKi5wJ3d0ehRexssylkNta6dwqN3IfuCzgP1D4PEfvYWqnSnTb8UpVnF+ZBDo2bTn4SRQKeMCjKBK9vhh/77Zjzyc/v3b3QtB/g6Fj03Hy7zs4FPpC4/me2oHBXT6Ks+nAXjaAsEK1Gk2oVk5C9GarKOTDWknRK8EiFfuqoKz99uxsfIQqSkJKPttmuXzA9xq1R58V3KZSek1izzqYG6AbOPXrs6vC5jLLt3Bir9+UZ9CuIxyqEzdxP2JSjlr2yyABfiGNNitPwwqlT0JkabuzwmigeDDBlPLdbiHTC12pPs+qzLTcg2JitoQmUeGOxmdRDR5CNu6VFJwEL0eMtuLW8v0myfh/JlSysWUDJgSExIwr07o9QM=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
